# Generated by Django 6.0 on 2025-12-29 19:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcbackend', '0002_ciudad_alter_lugar_place_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='punt_geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
